// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoF9cV0F1sHpWp3bt7tl38xJWpXPBOzoo',
    appId: '1:611556826987:web:744215e0d65c5cf286f62e',
    messagingSenderId: '611556826987',
    projectId: 'socialsignin-6eb46',
    authDomain: 'socialsignin-6eb46.firebaseapp.com',
    storageBucket: 'socialsignin-6eb46.appspot.com',
    measurementId: 'G-6C3F04FZ2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQvga-hPm5MSHLIF4lbjNMiE8boYG1nQI',
    appId: '1:611556826987:android:a5c386e285b6984786f62e',
    messagingSenderId: '611556826987',
    projectId: 'socialsignin-6eb46',
    storageBucket: 'socialsignin-6eb46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqb9zSBd2BL2ER7ECU4PC4_MjuhuY-Aqs',
    appId: '1:611556826987:ios:6e4907b09ada7bed86f62e',
    messagingSenderId: '611556826987',
    projectId: 'socialsignin-6eb46',
    storageBucket: 'socialsignin-6eb46.appspot.com',
    iosBundleId: 'com.example.googleSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqb9zSBd2BL2ER7ECU4PC4_MjuhuY-Aqs',
    appId: '1:611556826987:ios:e0d5d8507050442e86f62e',
    messagingSenderId: '611556826987',
    projectId: 'socialsignin-6eb46',
    storageBucket: 'socialsignin-6eb46.appspot.com',
    iosBundleId: 'com.example.googleSignin.RunnerTests',
  );
}
